---
driver:
  name: vagrant

provisioner:
  name: chef_solo
  require_chef_omnibus: true
  chef_omnibus_url: https://s3.amazonaws.com/articulate-chef/custom_chef_install.sh

platforms:
  - name: ubuntu
    driver_config:
      box: ubuntu-12.04.5-chef-12.6.0
      box_url: http://d30mo6j6uouwb9.cloudfront.net/vagrant-boxes/ubuntu-12.04.5-chef-12.6.0-virtualbox.box

      network:
      - ["private_network", {ip: "192.168.33.20"}]

suites:
  - name: source
    run_list:
      - recipe[duosecurity::default]
    attributes:
      duosecurity:
        install_type: "source"
  - name: package
    run_list:
      - recipe[duosecurity::default]
    attributes:
      duosecurity:
        install_type: "package"
